apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.deployment.name }}
  ports:
  - protocol: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.deployment.port }}
